name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: bash monitor.sh & sudo bash build_action.sh && rm monitor.sh

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact/